[package]
name = "rusqlite-derive"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.38.0", default-features = false }
rusqlite-derive-impl = { version = "=0.1.0", path = "../impl" }
